### ISSUE TITLE
[Question] How is ACH Handled if not through Plaid and 2 small-deposit confirmation?

### ISSUE THREAD

**Issue by tommymarshall** [c316/give#5]
Title says it all. Good looking app!

**Comment by c316** [comment]
@tommymarshall 

Some users of an out-of-business payment processor called "Balanced Payments" were rolled over to Stripe. At that time they were given an exemption. 

Stripe isn't giving any other exemptions that I know of. I've tried pretty hard to get them to move on that, but they haven't budged. I had a client who decided to process ACH manually through another processor. So Give allows for this scenario. 

![screen shot 2016-05-18 at 2 06 48 pm](https://cloud.githubusercontent.com/assets/3142974/15371588/d89dcebe-1d01-11e6-9920-79c5ac8739cc.png)


I have another developer who is interested in adding the micro-deposit confirmation to Give, no timeline yet though. 

Thanks for the compliment and feedback. I've worked really hard to make this usable, so let me know if I can help in any way.
